### ISSUE TITLE
Thanks for sharing and a little question ;)

### ISSUE THREAD

**Issue by vincegre** [arsaboo/homeassistant-config#1]
Thanks for sharing your config files for HA, it helped me really to tweak better mine but I have a little question:

I have seen that you use a !secret tag for all credentials to avoid to store them in config file but where are they then ? I have checked your whole git repository but didn't find out how it works :(

Thankr for explanation ;)

Vincèn

**Comment by CCOSTAN** [comment]
@vincegre Check out https://home-assistant.io/docs/configuration/secrets/

**Comment by vincegre** [comment]
@CCOSTAN Thanks ;)
