### ISSUE TITLE
Life360

### ISSUE THREAD

**Issue by JamesMcCarthy79** [arsaboo/homeassistant-config#15]
Hi,

First of all great repo thanks for sharing.

I am trying to implement your life360 package, I have the .py and package installed. I have set the life360 user/pass in the sensor of the package I'm getting only 'error' from that sensor and its state is never updated so its subscribing to a mqtt topic that isn't being updated. I couldn't find in your repo where you have set the mqtt server details to subscribe to.

Thanks James

**Comment by arsaboo** [comment]
It is all part of the sensor config https://github.com/arsaboo/homeassistant-config/blob/master/packages/life360.yaml#L14

**Comment by JamesMcCarthy79** [comment]
I saw that but it only sets the topic where would I set the broker details for the component to subscribe to? Can they be added to the sensor?

**Comment by JamesMcCarthy79** [comment]
I managed to add an automation to force owntracks updates and in conjunction with tasker have got owntracks to a reliable point so I will continue with this but I would have liked to get this component set up
