### ISSUE TITLE
Commute info

### ISSUE THREAD

**Issue by conradhagemans** [arsaboo/homeassistant-config#17]
Thanks for sharing all your Home assistant setup files. Helps a lot to get some inspiring ideas.
I saw that you have a commute/travel panel. I think you can improve the commute time with real-time information by using the Google Distance Matrix information. Real-time traffic information is calculated into the total travel time. And there is a standard Component to use it. Take a look at it: [Google Maps Travel Time](https://www.home-assistant.io/components/sensor.google_travel_time/)

**Comment by arsaboo** [comment]
That is exactly what I am [using](https://github.com/arsaboo/homeassistant-config/blob/master/sensor.yaml#L113) :wink:
