### ISSUE TITLE
Weather Custom Card - Weather Icon

### ISSUE THREAD

**Issue by zsarnett** [arsaboo/homeassistant-config#18]
## Expected Behavior
Weather is Sunny for a day in the week not today and the icon would be the Sunny Animated Icon while viewing at Night

(Every day that is not the current day would use the Day Icons instead of the Night Icons)

## Current Behavior
Weather is Sunny for a Day in the week not today and the icon shows the current SunLocation Animated Icon while viewing at night

![Screenshot of incorrect icon](https://user-images.githubusercontent.com/18730868/46057615-7c1c1a00-c124-11e8-94f9-36360b27e96b.png)

> I added the Time and Date into your card :)

![Forecast that corresponds with screenshot above](https://user-images.githubusercontent.com/18730868/46057632-a077f680-c124-11e8-9116-5cff9e6ec328.png)

I would expect it to only use the Sun Location on the current day of the week

## Possible Solution
After the first element in the map, reset the SunLocation to sunny. 

You could probably think of a better solution that is more dynamic

**Comment by arsaboo** [comment]
I hacked this together and have to admit that I barely understand the code. I will follow your lead here :)

**Comment by arsaboo** [comment]
Fixed with bram's weather card.
