### ISSUE TITLE
don't start

### ISSUE THREAD

**Issue by awaska** [arsaboo/homeassistant-config#20]
when i delete my .homeassistant dir and change with yours dir my home assistant don't start any more  

run on raspberrypi b

**Comment by iantrich** [comment]
you're trying to use his full configuration...?

**Comment by awaska** [comment]
yes

**Comment by iantrich** [comment]
not sure why you would expect it to work. you don't have his secrets, you don't have this devices, etc. You should be using other's configs as references. They are not replacements for your configuration.

**Comment by awaska** [comment]
but if i have some device in his configurator when i configure this all begin work?

**Comment by iantrich** [comment]
My point is that you should not copy his configuration and expect it to work. It is his setup. You should start with a base configuration and take parts that you find to be useful to you and lineup with what you have in your home.

**Comment by awaska** [comment]
ok thanks
