### ISSUE TITLE
add card-background-color style to (dark) themes

### ISSUE THREAD

**Issue by cchiapusio** [arsaboo/homeassistant-config#26]
Need to add 'card-background-color' style to frontend.yaml themes.

go to Configuration -> Integrations -> click any integration (on a dark theme) and the background of the theme is the inherited ffffff default and most dark themes have ffffff for text.

![Screenshot 2019-11-26 10 44 09](https://user-images.githubusercontent.com/6158033/69648713-cf943b80-1039-11ea-9648-2eddcfcd9356.png)

**Comment by arsaboo** [comment]
I think that should depend on the particular theme. Which theme are you using?

**Comment by uherting** [comment]
I found that adding a definition of  data-table-background-color to all themes helped me with my setup (hass.io 0.103.5) in the file frontend.yaml .
