### ISSUE TITLE
ip bans yaml

### ISSUE THREAD

**Issue by stevedub** [arsaboo/homeassistant-config#27]
Sorry not an issue but needed to message you.

I was looking at my ngnix logs on a secure server and noticed that two ips have been attacking my service. These two IPs are on your ip bans .yaml. How is this list generated? Thanks

**Comment by kfd14** [comment]
Sorry, I really have no idea what you are talking about.
________________________________

**Comment by stevedub** [comment]
You have a file in this repo called ipbans.yaml.

Did you manually input these IPs? Were they automatically generated? I'm
just wondering how they got there because they match the IPs I was
investigating.

Steven

**Comment by kfd14** [comment]
I'm really sorry if I did something wrong, I'm totally new at this. You might need to walk me through some of this. I didn't generate anything, to my knowledge and I'm not aware of creating any files either. Does any of this help you? Is there anything I can do on my end to investigate it further? A while back I accidentally pushed my HA config to Git but have since wiped and reloaded the entire program. Would that have created any of these issues?

**Comment by stevedub** [comment]
Hey Seth.

No problem at all. You have done nothing wrong. I am just looking for
information about a totally unrelated thing. You have given me all the info
I need. Thank you :)

**Comment by kfd14** [comment]
Okay, sounds good. Now you have me worried that something is wrong on my end.

**Comment by ascillato** [comment]
Ip bans yaml is an automatic generated file by home assistant. This is enabled only when you have ip banning configured in configuration.yaml.

In the case someone wants to log in but with incorrect username/password in your home assistant, its IP will show up in that file and home assistant will deny access to that IP. 

Also there is a problem with some cameras that can be wrongly added to IP banning. 

Search for http integration in home assistant documentation for more information.

**Comment by stevedub** [comment]
Thanks Adrian!

**Comment by kfd14** [comment]
I think I have at least a rudimentary understanding of IP bans now, thanks. I don't currently have that in my config, probably should though. This makes me wonder why my IP showed up in your bans list. And how you associated it with my email.  Was that a link through github?

**Comment by arsaboo** [comment]
Sorry for missing the conversation. The list was generated using the [Authenticated](https://github.com/custom-components/authenticated) custom component.
