### ISSUE TITLE
Hikvision pythlon api

### ISSUE THREAD

**Issue by glen20j** [arsaboo/homeassistant-config#37]
Hi arsaboo,

noticed you left an issue here
https://github.com/fbradyirl/hikvision/issues/2

editing "/srv/homeassistant/lib/python3.6/site-packages/requests/utils.py" specifically the function "check_header_validity" to just return will fix the issue you had.

no doubt you have moved way past this 6 years later!!

**Comment by arsaboo** [comment]
Haha....I don't even recall the issue anymore. Thanks for updating me through :)
