### ISSUE TITLE
thanks a lot for sharing and questions dialogflows

### ISSUE THREAD

**Issue by Oniric75** [arsaboo/homeassistant-config#4]
Hello,

thanks a lot for the sharing, lot of interesting information lacking in the official documentation.

i got some question on dialogflow : 
- how did you link it with your alexa ou googlehome ?
- do you got the annoying message telling you about "app test" too everytime it's invoked ?
- could you share your dialogflow script on google ?

i still got trouble identify how we linked our dialogflow (hass side) setup with google dialogflow (google side) and our third party (google home or alexa).

if you got a great "howto/walkthrough" on this subject i would be very pleased !

thanks anyway for the sharing :)

**Comment by arsaboo** [comment]
Thanks for your feedback and I am glad that you found the information useful. 

I used the [HA cloud for Alexa](https://home-assistant.io/components/cloud.alexa/) and the regular [Google Assistant component](https://home-assistant.io/components/google_assistant/) for Google Home. 

Yes, unfortunately, those annoying `test version` prompts are part of Dialogflow until we publish the app. I hope they allow us to customize those prompts for private skills. 

Are you looking for anything specific from DialogFlow? Unfortunately, it does not export cleanly like Alexa to share easily. All the intents [here](https://github.com/arsaboo/homeassistant-config/blob/master/intent_script.yaml) are configured in Dialogflow. Let me know what you are looking for.

**Comment by Oniric75** [comment]
Hello,

thanks a lot for your answer.

i'm struggling like i said with the link between hass, dialogflow and google home.

let's take an example in your config (thanks again for sharing!)

here is and extract of the config file from your hass :
>  GetInfofromHASS:
    speech:
      text: >
        {%- if SensorType.lower() == "temperature" -%}
          Temperature in the living room is {{ states('sensor.downstairs_temperature') }} degrees and upstairs temperature is {{ states('sensor.upstairs_temperature') }}.
        {%- elif SensorType.lower() == "humidity" -%}
          Humidity in the living room is {{ states.sensor.downstairs_humidity.state }} degrees and upstairs humidity is {{ states.sensor.upstairs_humidity.state }}.
        {%- elif SensorType.lower() == "traffic" or SensorType.lower() == "commute" -%}
          The fastest route to office takes about {{ states("sensor.morning_commute") }} minutes.
        {%- elif SensorType.lower() in ["evening traffic", "evening commute", "traffic to home"] -%}
          The fastest route to home takes about {{ states("sensor.alok_to_home") }} minutes.
        {%- endif -%}

what is configured in dialogflow to interact with it ?
i mean, in dialogflow, you have intent : "how are you today ?" and answers : "i'm fine and you" ?

when i read your config i see a tag "GetInfofromHASS" and a text that is most probably sent back to the google home. but how ? and how does dialogflow invoke this "GetInfofromHASS"
there is probably an intent linked to "SensorType.lower()" and a call back linked to "GetInfofromHASS" but i'm really struggling to understand it and i can't find a documentation on it on internet.

i hope you see what i mean and that you have time to help me. if you have a link where it's explain, please share it :)

thanks again.

**Comment by arsaboo** [comment]
Dialogflow communicates with your HA using webhooks. You will need to finish the setup for [Dialogflow](https://home-assistant.io/components/dialogflow/) so that it can communicate with your HA instance. Once you finish the initial setup and the two can communicate, you can use the intents.
