### ISSUE TITLE
Yr.no not working

### ISSUE THREAD

**Issue by vlaraort** [arsaboo/homeassistant-config#7]
Hi! First of all, good repo!

I am tring to replicate your yr.no forecast, in the configuration.yaml

```
  - platform: generic
    still_image_url: !secret meteogram_url
    content_type: 'image/svg+xml'
    name: Meteogram
```

I am using this URL: 

> https://www.yr.no/place/Spain/Madrid/Madrid/hour_by_hour.html

But its not working, Its displaying "image not available"

What am I doing wrong? Thanks!

**Comment by arsaboo** [comment]
That is the wrong URL. Your should use 

https://www.yr.no/place/Spain/Madrid/Madrid/meteogram.svg

**Comment by vlaraort** [comment]
Perfect, thank you very much!
