### ISSUE TITLE
YR.no

### ISSUE THREAD

**Issue by alibababa82** [arsaboo/homeassistant-config#9]
Hi,

I would like to ask you for your help, how to add secret meteogram_png_url? How the url should look like for https://www.yr.no/place/Czech_Republic/Prague/Prague/hour_by_hour.html?

Thank you very much in advance
M.

**Comment by alibababa82** [comment]
No need to reply, it should look like below and it´s working...
https://www.yr.no/place/Czech_Republic/Prague/Prague/meteogram.png

**Comment by alibababa82** [comment]
No need to reply, it should look like below and it´s working...
https://www.yr.no/place/Czech_Republic/Prague/Prague/meteogram.png

**Comment by disrupted** [comment]
I would even recommend using the .svg version since it's vector-based and therefore scalable https://www.yr.no/place/Czech_Republic/Prague/Prague/meteogram.svg
